### PR TITLE
Code Review Request

### PR DESCRIPTION
**Pull request by amiraabouhadid**
A list of projects organized by priority using Javascript's npm and webpack. Each project has a title, description, due date, and priority. You can view all projects and a project's details. Projects can be deleted.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑️🛑️🛑️🛑️**

Hello team
Amazing work on this project. I can tell you put in a lot of effort and it is amazing. Congrats👏️👏️👏️
however, let's make small changes and get it approved.

[REQUIRED]: All your files should be divided in modules, instead of separate functions.
[REQUIRED]: In variables.js, use import instead of require.

That's it👍️

Make the requested changes and ask for another review👍️👍️

You can contact me on slack at "NTWALI Heritier"

Happy coding💻️💻️

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑️🛑️**

Hello team,
Great work making the requested changes 👏️👏️,
however let's make a small change and get it approved.

[REQUIRED]: As specified in the project requirements and requested in the previous review, divide your codes in modules.
example of a module is `const Module = (()=> {
const func1 = () => {};
const func2 = () => {};
return {func1, func2};
}
)()`

then to use them, you can do `Module.func1() or Module.func2()`

This will help in code reusability.

Make the requested changes and ask for another review👍️👍️

You can contact me on slack at "NTWALI Heritier"

Happy coding💻️💻️

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Amira Abouhadid and  Shaher Mahmoud 


## To Highlight :tada:

1. You have mastered git-flow
2. You have descriptive git commit messages.


However, there are some changes that you need to make in order to get your project approved

- [x] Live link is not working
- [x] As the previous reviewer mentioned you need to divide the code into modules. You can have a look at this [tutorial](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)

<hr>

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS : REQUIRED CHANGES ♻️ 
@amiraabouhadid weldone for trying to implement the suggested changes by previous code reviewer,however changes is required

- [x] kindly remove commented codes from `navBar.js` and other commented code from other files.
- [x] Live link  still not working

### once specific changes made kindly request for another review

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Changes Required :recycle:
Hello team, 
**Well done on implementing the suggested changes from the previous reviews. However, some issues emerged while reviewing this project and it is important that you fix them before moving forward.** 
## To Improve
- [ ] The page only displays the title and menu icon and it not possible to create a project or tasks. Kindly fix this.
- [ ] The browser console is displaying errors. Kindly ensure that there are no errors in the console.

**You might have introduced a bug in your code while making changes since these issues were not raised in the previous reviews.** 

**Please make the above changes and ask for another review**

Feel free to leave a comment while mentioning me and I will be happy to reply.

### Happy Coding

_Slack: Oloo Moses_

**Comment by Shaher-11** [comment]
You need to open the page from the index.html file and there will be no errors

**Review by MkrtichSargsyan — APPROVED** [review]
## _Status:_ Approved  :hamster: :rocket:
Hello :wave:.

Awesome job on this project.:rocket: You have completed all the requested changes from the previous code reviewer.

You can go ahead and merge this branch to the base branch of this repo.
Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Pull request merged**
